name: Build JsonLib

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    # allows manual trigger

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clone EIV Nuget repository
      uses: actions/checkout@v4
      with:
        repository: ExtractIntoVoid/Nuget
        path: eiv_nuget
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Add eiv_nuget to nuget souce
      run: dotnet nuget add source --name eiv_nuget $env:GITHUB_WORKSPACE/eiv_nuget
      
    - name: Test
      run: dotnet test -c Release

    - name: Publish
      run: dotnet publish EIV_JsonLib/EIV_JsonLib.csproj -c Release -o Out
      
    - name: Pack
      run: dotnet pack EIV_JsonLib/EIV_JsonLib.csproj -c Release -o Out
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: EIV_JsonLib
        path: Out
        if-no-files-found: error
